baseURL = "https://www.coolector.net/"
languageCode = "en-us"
title = "Coolector"
theme = "hugo-theme-learn"
sidebarDescription = "Coolector description"
sidebarFreeText = "Sidebar information"

[params]
  themeVariant = "blue"

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[[menu.main]]
  name = "Coolector"
  post = "<span class='glyphicon glyphicon-fire'></span>"
  url = "https://www.coolector.net"
